#!/usr/bin/env python3
"""
Generate IconData.lua from the WoW community listfile.

Downloads the listfile CSV from the wowdev/wow-listfile GitHub releases,
filters for interface/icons/*.blp entries, and outputs a Lua table mapping
lowercase icon filenames (without path/extension) to their FileDataIDs.

Usage:
    python3 tools/generate_icondata.py
"""

import csv
import io
import os
import sys
import urllib.request

LISTFILE_URL = "https://github.com/wowdev/wow-listfile/releases/latest/download/community-listfile.csv"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "..", "IconData.lua")

ICON_PREFIX = "interface/icons/"
ICON_SUFFIX = ".blp"


def download_listfile():
    print(f"Downloading listfile from {LISTFILE_URL} ...")
    req = urllib.request.Request(LISTFILE_URL, headers={"User-Agent": "MacroIconSearch/1.0"})
    with urllib.request.urlopen(req) as resp:
        data = resp.read().decode("utf-8", errors="replace")
    print(f"Downloaded {len(data)} bytes")
    return data


def parse_icons(listfile_text):
    """Parse the listfile CSV and extract icon entries."""
    icons = {}
    reader = csv.reader(io.StringIO(listfile_text), delimiter=";")
    for row in reader:
        if len(row) < 2:
            continue
        file_id_str, filepath = row[0], row[1]
        filepath_lower = filepath.lower().strip()
        if filepath_lower.startswith(ICON_PREFIX) and filepath_lower.endswith(ICON_SUFFIX):
            # Extract filename without path and extension
            name = filepath_lower[len(ICON_PREFIX):-len(ICON_SUFFIX)]
            # Skip entries with subdirectories under icons/
            if "/" in name:
                continue
            try:
                file_id = int(file_id_str.strip())
            except ValueError:
                continue
            icons[name] = file_id
    return icons


def write_lua(icons, output_path):
    """Write the icon data as a Lua table."""
    output_path = os.path.normpath(output_path)
    with open(output_path, "w", newline="\n") as f:
        f.write("-- Generated by tools/generate_icondata.py — DO NOT EDIT\n")
        f.write("-- Contains %d icon filename -> FileDataID mappings\n" % len(icons))
        f.write("local _, MIS = ...\n")
        f.write("MIS.IconFileNames = {\n")
        for name in sorted(icons.keys()):
            # Lua string keys with brackets to handle any special chars
            f.write('    ["%s"] = %d,\n' % (name, icons[name]))
        f.write("}\n")
    print(f"Wrote {len(icons)} entries to {output_path}")


def main():
    listfile_text = download_listfile()
    icons = parse_icons(listfile_text)
    if not icons:
        print("ERROR: No icon entries found in listfile!", file=sys.stderr)
        sys.exit(1)
    print(f"Found {len(icons)} icon entries")
    write_lua(icons, OUTPUT_PATH)


if __name__ == "__main__":
    main()
